name: Test the project and update the test-date

on:
  # push:
  #  branches:
  #   - main
  # schedule:
  #   - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: 'Set start time'
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: 'Checkout Repo'
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: 'Generate key and update the test time'
        run: |
          ACCOUNT=0
          KEY=1
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git clone --depth 1 https://github.com/rzc0d3r/ESET-KeyGen.git
          cd ESET-KeyGen
          sudo apt update
          sudo apt install -y python3-pip
          sudo pip install -r requirements.txt
          echo "Test results:" >> $GITHUB_STEP_SUMMARY
          if [[ ${ACCOUNT} != 0 ]]
          then
            for ((attempt=1;attempt<=${ACCOUNT};++attempt))
            do
              python3 main.py --chrome --account --email-api guerrillamail --skip-update-check
            done
            echo -e "\nAccounts generated:" >> $GITHUB_STEP_SUMMARY
            cat ./*ACCOUNTS.txt >> $GITHUB_STEP_SUMMARY
          fi
          if [[ ${KEY} != 0 ]]
          then
            for ((attempt=1;attempt<=${KEY};++attempt))
            do
              python3 main.py --chrome --key --email-api guerrillamail --skip-update-check
            done
            echo -e "\nKeys generated:" >> $GITHUB_STEP_SUMMARY
            cat ./*KEYS.txt >> $GITHUB_STEP_SUMMARY
            MSG1=$(sed -n '6p' ./*KEYS.txt)
            echo MSG1=$MSG1 >> $GITHUB_ENV 
            MSG2=$(sed -n '7p' ./*KEYS.txt)
            echo MSG2=$MSG2 >> $GITHUB_ENV
            MSG3=$(sed -n '8p' ./*KEYS.txt)
            echo MSG3=$MSG3 >> $GITHUB_ENV
          fi
          cd ${{ github.workspace }}
          sed -i '/^ESET-KeyGen - Trial-Key & Account generator/ c\ESET-KeyGen - Trial-Key & Account generator for ESET Antivirus (last test was on '"$(date -u --date='3 hours' +"%d.%m.%Y at %H:%M UTC+3")"')' README.md
          sudo rm -r ESET-KeyGen
          git pull
          git commit -m "Update test time" -a

      - name: Push changes to the repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Calculate elapsed time
        run: |
          END_TIME=$(date +%s)
          ELAPSED=$((END_TIME - START_TIME))
          MINUTES=$((ELAPSED / 60))
          SECONDS=$((ELAPSED % 60))
          echo "ELAPSED_TIME_FORMATTED=${MINUTES}m ${SECONDS}s" >> $GITHUB_ENV

      - name: Send success message to Telegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ Успешно:
            Время выполнения: ${{ env.ELAPSED_TIME_FORMATTED }}
            ${{ env.MSG1 }}
            <b>${{ env.MSG2 }}</b>
            ${{ env.MSG3 }}
          parse_mode: html

      - name: Send failure message to Telegram
        if: failure()
        uses: appleboy/telegram-action@master 
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ Ошибка в GitHub Actions!
            Время выполнения: ${{ env.ELAPSED_TIME_FORMATTED }}
            Репозиторий: ${{ github.repository }}
            Ветка: ${{ github.ref }}
            Коммит: ${{ github.sha }}
            Workflow: ${{ github.workflow }}
            URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
